#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Build third-party components
[[ -d ./build-temp/distfiles ]] || die "Make sure the required dependency files are in ./build-temp/distfiles, or run build-scripts/dist-fetch to get them from your /usr/portage."

source ./support/build-scripts/dist-versions || die
cd ./build-temp/build || die

unpackedDir="$(readlink -f .)/../unpacked"

echo "Building wat2wasm"
cp -r "$unpackedDir/wabt-$myWabtVersion" ./
cd ./wabt-"$myWabtVersion" || die

echo "Building wat2wasm: Preparing dependencies"
cp -r "$unpackedDir/emscripten-$myEmscriptenCommit" "./emscripten" || die
cp -r "$unpackedDir/ply-${myPlyVersion}" "./emscripten/third_party/ply" || die
rm -rf "./third_party"
mkdir "./third_party" || die "Error creating empty third_party directory"
cp -r "$unpackedDir/googletest-release-${myGoogletestVersion}" "./third_party/gtest" || die
cp -r "$unpackedDir/ply-${myPlyVersion}" "./third_party/ply" || die
cp -r "$unpackedDir/testsuite-${myTestsuiteCommit}" "./third_party/testsuite" || die

rm -rf "./src/prebuilt"
mkdir "./src/prebuilt" || die "Error creating empty src/prebuilt directory"
re2c -W -Werror --no-generation-date -bc8 -o src/wast-lexer-gen.cc src/wast-lexer.cc
src/wasm2c_tmpl.py -o src/wasm2c.include.c src/wasm2c.c.tmpl
src/wasm2c_tmpl.py -o src/wasm2c.include.h src/wasm2c.h.tmpl
rm src/wasm2c.{c,h}.tmpl src/wasm2c_tmpl.py src/wabt.post.js
(
    cd "$(readlink -f .)" || die
    EM_CONFIG="$(readlink -f .)/.emscripten"
    export EM_CONFIG
    rm -f "$EM_CONFIG"
    rm -f ./emscripten/.emscripten
    ln -s "$EM_CONFIG" ./emscripten/.emscripten # shared:ERROR: File /nvme0n1p5/build-temp/build/wabt-1.0.8/emscripten/.emscripten passed to --em-config does not exist!
    EM_CACHE="$(readlink -f .)/.emscripten_cache"
    export EM_CACHE
    rm -rf "$EM_CACHE"
    mkdir "$EM_CACHE"
    mkdir "$EM_CACHE/wasm_o"
    #EMCC_DEBUG="1"
    #export EMCC_DEBUG
    EM_PORTS="$(readlink -f .)/.emscripten_ports"
    export EM_PORTS
    rm -rf "$EM_PORTS"
    mkdir "$EM_PORTS"
    mkdir "$EM_PORTS/binaryen"
    # Based on https://github.com/emscripten-core/emscripten/blob/c53838be5d58a03d947d19047e12ac07a02afa7d/tools/ports/binaryen.py and https://github.com/emscripten-core/emscripten/blob/ef230f55772b7a2b2d4c6a29b8f1cde915bd8e3f/tools/system_libs.py
    cp -r "$unpackedDir/binaryen-version_${myBinaryenVersion}" "$EM_PORTS/binaryen/"
    (
        echo "Building wat2wasm: Building binaryen"
        cd "$EM_PORTS/binaryen/binaryen-version_${myBinaryenVersion}/"
      #  cmake -DCMAKE_BUILD_TYPE=Release .
       # cmake --build .
        echo "${myBinaryenVersion}" > ../tag.txt
        echo "${myBinaryenVersion}" > "$EM_CACHE/wasm_o/binaryen_tag_version_${myBinaryenVersion}.txt"
        cp "$unpackedDir/binaryen-${myBinaryenVersion}.zip" "$EM_PORTS/binaryen.zip"
    )

    echo 'import os' >> "$EM_CONFIG"
    echo 'EMSCRIPTEN_ROOT = '\'"$(readlink -f .)"\' >> "$EM_CONFIG"
    echo 'LLVM_ROOT = '\''/usr/lib/llvm/9/bin'\' >> "$EM_CONFIG"
    echo 'BINARYEN_ROOT = '\'\' >> "$EM_CONFIG"
    echo 'NODE_JS = '\''/usr/bin/node'\' >> "$EM_CONFIG"
    echo 'TEMP_DIR = '\''/tmp'\' >> "$EM_CONFIG"
    echo 'COMPILER_ENGINE = NODE_JS' >> "$EM_CONFIG" # Does it really need this
    echo "COMPILER_OPTS = ['-O0']" >> "$EM_CONFIG"

    # Stub out minify_wasm_js method to remove (some of the) node.js dependency
    # https://nixtricks.wordpress.com/2013/01/09/sed-delete-the-lines-lying-in-between-two-patterns/
    sed '/def\ minify_wasm_js/,/run\ binaryen'\\\''s\ wasm-metadce/{//!d}' ./emscripten/tools/shared.py | sponge ./emscripten/tools/shared.py
die
    echo "Building wat2wasm: Building emscripten built-in packages (libc etc)"
    ./emscripten/embuilder.py build libc
    ./emscripten/embuilder.py build libc-wasm
    ./emscripten/embuilder.py build libc++_noexcept
    ./emscripten/embuilder.py build libc++abi
    ./emscripten/embuilder.py build compiler_rt_wasm
    ./emscripten/embuilder.py build dlmalloc
    ./emscripten/embuilder.py build pthreads_stub
    ./emscripten/embuilder.py build libc-extras

    echo "Building wat2wasm: Compiling"
    make demo
)
#for file in src/*.cc; do
    #clang++ -v -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -I. -Xclang -isystem../emscripten-${myEmscriptenCommit}/system/include/libcxx -Xclang -isystem../emscripten-${myEmscriptenCommit}/system/include/libc -std=c++11 -D_LIBCPP_ABI_VERSION=2 -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -g -Wold-style-cast -Wall -Wextra -Wno-unused-parameter -Wpointer-arith -Wuninitialized -fno-exceptions -o "$file".o -c -Ofast --target=wasm32-unknown-unknown-wasm "$file"
#done

touch ../dist-build-ready
