#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Retrieve third-party files

source ./support/build-scripts/dist-versions || die

rm -rf ./build-temp/distfiles/
mkdir -p ./build-temp/distfiles/

rm -rf ./build-temp/build
mkdir -p ./build-temp/build

dist() {
    echo "Copying distfile: $1"
    rsync -a --checksum /usr/portage/distfiles/"$1" ./build-temp/distfiles/ &>/dev/null
    rsync -a --checksum ./build-temp/distfiles/"$1" ./build-temp/build/ &>/dev/null
}

dist emscripten-"$myEmscriptenCommit".tar.gz
#dist llvm-project-"$myLlvmCommit".tar.gz
# wabt and its build-time dependencies
dist wabt-"$myWabtVersion".tar.gz
#dist googletest-"$myGoogletestVersion".tar.gz
#dist python-lex-yacc-"$myPlyVersion".tar.gz
#dist WebAssembly-testsuite-"$myTestsuiteCommit".tar.gz

(
cd ./build-temp/build || die

#echo "Unpacking LLVM"
#tar xozf ./llvm-project-"$myLlvmCommit".tar.gz

echo "Unpacking Emscripten"
tar xozf ./emscripten-"$myEmscriptenCommit".tar.gz
rm ./emscripten-"$myEmscriptenCommit".tar.gz

echo "Unpacking wabt"
tar xozf ./wabt-"$myWabtVersion".tar.gz
rm ./wabt-"$myWabtVersion".tar.gz
rm -r ./wabt-"$myWabtVersion"/src/prebuilt
mv ./wabt-"$myWabtVersion"/src/ ./
rm -r ./wabt-"$myWabtVersion"
mkdir ./wabt-"$myWabtVersion"
mv ./src ./wabt-"$myWabtVersion"/
)

./support/dist-build
