#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Retrieve third-party files

source ./support/build-scripts/dist-versions || die

rm -rf ./build-temp/distfiles/
mkdir -p ./build-temp/distfiles/

if [[ -d /usr/portage/distfiles ]]; then
    dist() {
        echo "Copying distfile: $1"
        rsync -a --checksum /usr/portage/distfiles/"$1" ./build-temp/distfiles/ &>/dev/null
    }

    # wabt and its build-time dependencies
    dist emscripten-"$myEmscriptenCommit".tar.gz
    dist binaryen-"$myBinaryenVersion".tar.gz
    dist binaryen-"$myBinaryenVersion".zip
    dist wabt-"$myWabtVersion".tar.gz
    dist googletest-"$myGoogletestVersion".tar.gz
    dist python-lex-yacc-"$myPlyVersion".tar.gz
    dist WebAssembly-testsuite-"$myTestsuiteCommit".tar.gz
else
    
fi

./support/dist-build
