#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# This generates the list of tarballs for node.js dependencies.

if [[ "$1" == "--bootstrap" ]]; then
    shift
    (
        mkdir -p ./build-temp/nodejs-build-temp
        cd ./build-temp/nodejs-build-temp
        npm i npm-remote-ls
    )
else
    if [[ "$1" == "--quick" ]]; then
        ./support/dist-build
    fi
fi

mkdir -p support/build-nodejs-tarballs-process

./build-temp/nodejs-build-temp/node_modules/npm-remote-ls/bin/npm-remote-ls.js npm-remote-ls > support/build-nodejs-tarballs-process/npm-remote-ls.deps
./build-temp/nodejs-build-temp/node_modules/npm-remote-ls/bin/npm-remote-ls.js js-ipfs > support/build-nodejs-tarballs-process/js-ipfs.deps

cat support/build-nodejs-tarballs-process/*.deps > support/build-nodejs-tarballs-process/all.deps-merged-pre
sed 's/^[ ─└├]//g' support/build-nodejs-tarballs-process/all.deps-merged-pre > support/build-nodejs-tarballs-process/all.deps-merged-sed
sort -u -o support/build-nodejs-tarballs-process/all.deps-merged-filtered support/build-nodejs-tarballs-process/all.deps-merged-filtered
sed -E 's/-(.)/\U\1/g' support/build-nodejs-tarballs-process/all.deps-merged-filtered > support/build-nodejs-tarballs-process/all.deps-merged-filtered-camelcase
sed 's/^([^@]+)@(.+)$/my\1Version="\2"/g' support/build-nodejs-tarballs-process/all.deps-merged-filtered-camelcase > support/build-nodejs-tarballs-process/all.deps-merged-versions

sed 's/^([^@]+)@(.+)$/my\1Version="\2"/g' support/build-nodejs-tarballs-process/all.deps-merged-filtered-camelcase > support/build-nodejs-tarballs-process/all.deps-dist-urls
sed 's/^([^@]+)@(.+)$/my\1Version="\2"/g' support/build-nodejs-tarballs-process/all.deps-merged-filtered-camelcase > support/build-nodejs-tarballs-process/all.deps-dist-wgets
sed 's/^([^@]+)@(.+)$/my\1Version="\2"/g' support/build-nodejs-tarballs-process/all.deps-merged-filtered-camelcase > support/build-nodejs-tarballs-process/all.deps-copy-cmds

if [[ "$1" != "--debug" ]]; then
    rm support/build-nodejs-tarballs-process/npm-remote-ls.deps
    rm support/build-nodejs-tarballs-process/js-ipfs.deps
    rm support/build-nodejs-tarballs-process/all.deps-merged-pre
    rm support/build-nodejs-tarballs-process/all.deps-merged-sed
    rm support/build-nodejs-tarballs-process/all.deps-merged-filtered
    rm support/build-nodejs-tarballs-process/all.deps-merged-filtered-camelcase
fi
