#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Retrieve third-party files

rm -r ./distfiles/

dist() {
    echo "Copying distfile: $1"
    rsync -av --checksum /usr/portage/distfiles/"$1" ./distfiles/
}

dist googletest-1.8.1.tar.gz
dist wabt-1.0.8-linux.tar.gz
dist python-lex-yacc-3.11.tar.gz
dist WebAssembly-testsuite-89cc463fa1251449d7974086a34ef0dc100b1582.tar.gz
