#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

#NOTE: MAINTENANCE: Manual error printing
if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
    printf '%b' '\033[1;31m' >&2
    echo "ERROR: ember-shared is not properly installed! It must be installed before installing eite." >&2
    printf '%b' '\033[0m' >&2
    exit 1
fi

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR

skipConfigFile="false"
if [[ "$1" == "--skip-config-file" ]]; then
    skipConfigFile="true"
    shift
fi

#echo 1 "$1" 2 "$2" 3 "$3" 4 "$4" 5 "$5" 6 "$6" 7 "$7" 8 "$8" 9 "$9"
if [[ -n "$1" ]]; then
    eiteDestdir="$1"
    shift
fi
if [[ "$1" == "--skip-config-file" ]]; then
    skipConfigFile="true"
    shift
fi
if [[ -n "$1" ]]; then
    eitePrefix="$1"
    shift
fi
if [[ -n "$1" ]]; then
    eiteCapPrefix="$1"
    shift
fi
if [[ -n "$1" ]]; then
    eiteExecPrefix="$1"
    shift
fi
if [[ -n "$1" ]]; then
    eiteBindir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    eiteDatarootdir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    eiteDatadir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    eiteSysconfdir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    eiteSharedstatedir="$1"
    shift
fi
if ! [[ -n "$eitePrefix" ]]; then
    if ! [[ -n "$eiteCapPrefix" ]]; then
        eitePrefix="$eiteDestdir"/usr/local
    else
        eitePrefix="$eiteCapPrefix"
    fi
fi
#echo "eitePrefix: $eitePrefix"
if ! [[ -n "$eiteExecPrefix" ]]; then
    eiteExecPrefix="$eitePrefix"
fi
#echo "eiteExecPrefix: $eiteExecPrefix"
if ! [[ -n "$eiteBindir" ]]; then
    eiteBindir="$eiteExecPrefix"/bin
fi
#echo "eiteBindir: $eiteBindir"
if ! [[ -n "$eiteDatarootdir" ]]; then
    eiteDatarootdir="$eitePrefix"/share
fi
#echo "eiteDatarootdir: $eiteDatarootdir"
if ! [[ -n "$eiteDatadir" ]]; then
    eiteDatadir="$eiteDatarootdir"
fi
#echo "eiteDatadir: $eiteDatadir"
if ! [[ -n "$eiteSysconfdir" ]]; then
    eiteSysconfdir="$eitePrefix"/etc
fi
#echo "eiteSysconfdir: $eiteSysconfdir"
if ! [[ -n "$eiteSharedstatedir" ]]; then
    eiteSharedstatedir="$eitePrefix"/var
fi
#echo "eiteSharedstatedir: $eiteSharedstatedir"

mkdir -p "$eiteDatadir/eite"
mkdir -p "$eiteDatadir/doc/eite"
mkdir -p "$eiteBindir"
chmod +x scripts/*
cp scripts/* "$eiteBindir/"
mkdir -p "$eiteSysconfdir"

cp -r data "$eiteDatadir/eite/"
cp -r logic "$eiteDatadir/eite/"
cp -r tests "$eiteDatadir/eite/"
cp -r docs/* "$eiteDatadir/doc/eite/"

cp "$eiteDatarootdir"/javascript/PapaParse/papaparse.js web/

cp -r web "$eiteDatadir/eite/"
