#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
set -x

#NOTE: MAINTENANCE: Manual error printing
if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
    printf '%b' '\033[1;31m' >&2
    echo "ERROR: ember-shared is not properly installed! It must be installed before installing eite." >&2
    printf '%b' '\033[0m' >&2
    exit 1
fi

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR

skipConfigFile="false"
if [[ "$1" == "--skip-config-file" ]]; then
    skipConfigFile="true"
    shift
fi

overrideInstalledAppDataDir="/usr/share"
overrideInstalledAppDataDirArg="${1#*=}"
if [[ "$1" == "--override-data-dir="* ]] && [[ -n "$overrideInstalledAppDataDirArg" ]]; then
    overrideInstalledAppDataDir="$overrideInstalledAppDataDirArg"
fi
shift

emberPrefix="$(<support/prefix)" || true
emberMandir="$(<support/mandir)" || true
emberInfodir="$(<support/prefix)" || true
emberDatadir="$(<support/prefix)" || true
emberSysconfdir="$(<support/prefix)" || true
emberLocalstatedir="$(<support/prefix)" || true

#echo 1 "$1" 2 "$2" 3 "$3" 4 "$4" 5 "$5" 6 "$6" 7 "$7" 8 "$8" 9 "$9"
if [[ -n "$1" ]]; then
    emberDestdir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    emberPrefix="$1"
    shift
fi
if [[ -n "$1" ]]; then
    emberCapPrefix="$1"
    shift
fi
if [[ -n "$1" ]]; then
    emberExecPrefix="$1"
    shift
fi
if [[ -n "$1" ]]; then
    emberBindir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    emberDatarootdir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    emberDatadir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    emberSysconfdir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    emberSharedstatedir="$1"
    shift
fi
if ! [[ -n "$emberPrefix" ]]; then
    if ! [[ -n "$emberCapPrefix" ]]; then
        emberPrefix="$emberDestdir"/usr/local
    else
        emberPrefix="$emberCapPrefix"
    fi
fi
echo "emberPrefix: $emberPrefix"
if ! [[ -n "$emberExecPrefix" ]]; then
    emberExecPrefix="$emberPrefix"
fi
echo "emberExecPrefix: $emberExecPrefix"
if ! [[ -n "$emberBindir" ]]; then
    emberBindir="$emberExecPrefix"/bin
fi
echo "emberBindir: $emberBindir"
if ! [[ -n "$emberDatarootdir" ]]; then
    emberDatarootdir="$emberPrefix"/share
fi
echo "emberDatarootdir: $emberDatarootdir"
if ! [[ -n "$emberDatadir" ]]; then
    emberDatadir="$emberDatarootdir"
fi
echo "emberDatadir: $emberDatadir"
if ! [[ -n "$emberSysconfdir" ]]; then
    emberSysconfdir="$emberPrefix"/etc
fi
echo "emberSysconfdir: $emberSysconfdir"
if ! [[ -n "$emberSharedstatedir" ]]; then
    emberSharedstatedir="$emberPrefix"/var
fi
echo "emberSharedstatedir: $emberSharedstatedir"

mkdir -p "$emberDatadir/eite"
mkdir -p "$emberDatadir/doc/eite"
mkdir -p "$emberBindir"
chmod +x cli/*
cp cli/* "$emberBindir/"
mkdir -p "$emberSysconfdir"

cp -r data "$emberDatadir/eite/"
cp -r logic "$emberDatadir/eite/"
cp -r tests "$emberDatadir/eite/"
cp -r docs/* "$emberDatadir/doc/eite/"

rm web/papaparse.js
cp "$overrideInstalledAppDataDir"/javascript/PapaParse/papaparse.js web/

cp -r web "$emberDatadir/eite/"
