#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

tempDirPath="$(tempDir)"
cp -r "$(dirname "$(crystallize-getconf ConfigLocation)")/usr/eite/tests" "$tempDirPath/"
