#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup_core &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup_core could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

(
cd tests || die

runTestForEachLanguage() {
    if [[ "-v" == "$1" ]]; then

    runTest "stagel/bash/$1"
    runTest "stagel/js/$1"
}

runTest stagel/no-codegen/routine-minimal
runTest stagel/no-codegen/routine-newline-in-body
runTest stagel/no-codegen/if-with-indented
runTest stagel/no-codegen/if-with-comment
runTest stagel/no-codegen/routine-with-if
runTest stagel/no-codegen/loop-block-longhand
runTest stagel/no-codegen/loop-block
runTest stagel/no-codegen/routine-fizzbuzz

runTestForEachLanguage -v arglist-two-nested
runTestForEachLanguage arglist-three-nested
runTestForEachLanguage routine-minimal
runTestForEachLanguage two-routines
runTestForEachLanguage if-statement
runTestForEachLanguage if-one-command
runTestForEachLanguage if-with-inner-block
runTestForEachLanguage routine-fbSwitcher-return-type
runTestForEachLanguage routine-fizzbuzz-fbSwitcher
runTestForEachLanguage routine-with-if
runTestForEachLanguage declare-n
runTestForEachLanguage set-number-add-no-routine
runTestForEachLanguage set-number-add
runTestForEachLanguage set-to-str-routine-with-new
runTestForEachLanguage set-to-str-routine-invocation
#runTest -v stagel/js/routine-fizzbuzz
runTestForEachLanguage logical-or
runTestForEachLanguage generic-parameter
runTestForEachLanguage generic-ga-gi-parameter
runTestForEachLanguage array-s
runTestForEachLanguage array-zero-only
runTestForEachLanguage bool-literal
runTestForEachLanguage str-escape-literal
runTestForEachLanguage else
runTestForEachLanguage elif
runTestForEachLanguage arglist-inline-end
runTestForEachLanguage loop-block-longhand
runTestForEachLanguage loop-block
runTestForEachLanguage wasm-tests

reportTests
)
