#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

cd tests || die

runTest stagel/no-codegen/routine-minimal
runTest stagel/no-codegen/routine-newline-in-body
runTest stagel/no-codegen/if-with-indented
runTest stagel/no-codegen/if-with-comment
runTest stagel/no-codegen/routine-with-if
#runTest stagel/no-codegen/routine-fizzbuzz
runTest stagel/js/arglist-two-nested
runTest stagel/js/arglist-three-nested
runTest stagel/js/routine-minimal
runTest stagel/js/two-routines
runTest stagel/js/bare-block
runTest stagel/js/if-statement
runTest stagel/js/if-one-command
runTest stagel/js/if-with-indented
runTest stagel/js/if-with-comment
runTest stagel/js/if-with-comment-and-inner-block
runTest stagel/js/routine-fbSwitcher-return-type
runTest stagel/js/routine-fizzbuzz-fbSwitcher
runTest stagel/js/routine-with-if
runTest stagel/js/declare-n
runTest stagel/js/set-number-add-no-routine
runTest stagel/js/set-number-add
runTest stagel/js/set-to-str-routine-with-new
runTest stagel/js/set-to-str-routine-invocation
runTest stagel/js/routine-fizzbuzz
runTest stagel/js/logical-or
runTest stagel/js/generic-parameter
runTest stagel/js/array-s
runTest stagel/js/bool-literal
runTest stagel/js/else
runTest stagel/js/elif

reportTests
