#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

cd tests || die

runTest stagel/no-codegen/routine-minimal
runTest stagel/no-codegen/if-with-indented
#runTest stagel/no-codegen/routine-fizzbuzz
runTest stagel/js/routine-minimal
runTest stagel/js/two-routines
runTest stagel/js/bare-block
runTest stagel/js/if-statement
runTest stagel/js/if-one-command
runTest stagel/js/if-with-indented
runTest stagel/js/if-with-comment
runTest stagel/js/if-with-comment-and-inner-block
runTest stagel/js/routine-fbSwitcher-return-type
runTest stagel/js/routine-fizzbuzz-fbSwitcher
runTest -v stagel/js/routine-with-if
#runTest -v stagel/js/routine-fizzbuzz

reportTests
