#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Takes a StageL file as first argument, and prints out equivalent code in the language of the second argument (bash/js).

input="$1"
targetLang="$2"

tokens=()

# First, break up the input into tokens in the tokens array. This doesn't support streaming, so isn't good for long documents, but should suffice for now. The format should be streamable to other formats; this was just easier to implement for now.

parserState="token"
currentIndentLevel="0"
countingIndentSpaces="true"
indentSpacesCounted="0"
lineNumber="1"
columnNumber="1"

pushToken() {
    if [[ -n "${tokens[-1]}" ]] || [[ -n "${tokens[-2]}" ]]; then
        # There's a token in the last slot in the tokens array, so make a new slot for the next one
        tokens+=("$lineNumber:$columnNumber:$currentIndentLevel")
        tokens+=("")
        tokens+=("")
    fi
    tokens[-2]="$1"
    tokens[-1]="$2"
    # Make a new slot for whatever happens next
    tokens+=("$lineNumber:$columnNumber:$currentIndentLevel")
    tokens+=("")
    tokens+=("")
}

insertToken() {
    local insertAfter="$1"
    local newTokenType="$2"
    local newToken="$3"
    local tokensTemp=("${tokens[@]:0:insertAfter}")
    #print_r "${tokensTemp[@]}" >&2
    tokensTemp+=("${tokens[$((insertAfter - 2))]}")
    tokensTemp+=("$newTokenType")
    #print_r "${tokensTemp[@]}" >&2
    tokensTemp+=("$newToken")
    #print_r "${tokensTemp[@]}" >&2
    tokensTemp+=("${tokens[@]:insertAfter}")
    #print_r "${tokensTemp[@]}" >&2
    tokens=("${tokensTemp[@]}")
    #print_r "${tokens[@]}" >&2
}

# We need a dummy token at the beginning so we can insertToken after it (otherwise it would be inserting after something that doesn't exist)
tokens+=("$lineNumber:$columnNumber:$currentIndentLevel")
tokens+=("start-document")
tokens+=("")

# Add empty slots to the array for the first token
tokens+=("$lineNumber:$columnNumber:$currentIndentLevel") # Line/column/depth goes in first slot
tokens+=("") # Token type goes in second slot
tokens+=("") # Token content goes in third slot

while read -r byte; do
    byte=$(( 16#$byte )) # Convert to decimal
    if asciiIsNewline "$byte" || { [[ "$parserState" == "token" ]] && [[ "$byte" == "59" ]]; }; then
        pushToken newline ""
        lineNumber=$(( lineNumber + 1 ))
        columnNumber=1
    else
        columnNumber=$(( columnNumber + 1 ))
    fi
    #declare -p tokens >&2
    tokenCount="${#tokens[@]}" >&2
    comment='
    if [[ $lineNumber -eq 3 ]]; then
        set -x
    fi
    if [[ $lineNumber -eq 4 ]]; then
        die
    fi
    '
    case $parserState in
    token)
        if [[ "$countingIndentSpaces" == "true" ]]; then
            if asciiIsPrintable "$byte" && [[ "$byte" != "32" ]]; then
                if [[ $(( indentSpacesCounted % 4 )) -eq 0 ]] && [[ "$indentSpacesCounted" -lt $(( currentIndentLevel * 4 )) ]]; then
                    for (( i=0; i<=$(( currentIndentLevel - ( indentSpacesCounted / 4 ) )); i++ )); do
                        pushToken dedent ""
                        currentIndentLevel=$(( currentIndentLevel - 1 ))
                    done
                elif [[ "$indentSpacesCounted" -eq $(( currentIndentLevel * 4 )) ]]; then
                    true # The expected number of indent spaces was found; do nothing
                elif [[ "$indentSpacesCounted" -eq $(( ( currentIndentLevel + 1 ) * 4 )) ]]; then
                    pushToken "indent" ""
                    currentIndentLevel=$(( currentIndentLevel + 1 ))
                else
                    die "Found $indentSpacesCounted spaces on line $lineNumber, column $columnNumber, but the current indentation level would expect $(( currentIndentLevel * 4 )) spaces."
                fi
                countingIndentSpaces="false"
                indentSpacesCounted="0"
            elif [[ "$byte" == "32" ]]; then
                indentSpacesCounted=$(( indentSpacesCounted + 1 ))
            fi
        fi

        if asciiIsNewline "$byte"; then
            countingIndentSpaces="true"
        fi

        if asciiIsLetter "$byte" || asciiIsDigit "$byte" || [[ "$byte" == 45 ]] || [[ "$byte" == 47 ]]; then
            [[ -z "${tokens[-1]}" ]] && tokens[-3]="$lineNumber:$columnNumber:$currentIndentLevel"
            tokens[-1]="${tokens[-1]} $byte"
        elif asciiIsSpace "$byte"; then
            if [[ -n "${tokens[-1]}" ]]; then
                # End of token.
                # There's a token in the last slot in the tokens array, so make a new slot for the next one
                tokens+=("$lineNumber:$columnNumber:$currentIndentLevel")
                tokens+=("")
                tokens+=("")
            fi
        elif asciiIsNewline "$byte"; then
            # End of token
            if [[ -n "${tokens[-1]}" ]]; then
                tokens+=("$lineNumber:$columnNumber:$currentIndentLevel")
                tokens+=("")
                tokens+=("")
            fi
        elif [[ "$byte" == 39 ]]; then
            parserState="literal-s"
            tokens[-3]="$lineNumber:$columnNumber:$currentIndentLevel"
            tokens[-2]="literal-s"
        elif [[ "$byte" == 35 ]]; then
            parserState="comment"
            tokens[-3]="$lineNumber:$columnNumber:$currentIndentLevel"
            tokens[-2]="comment"
        else
            die "Unexpected byte $byte in basic token."
        fi
        ;;
    comment)
        if asciiIsNewline "$byte"; then
            parserState="token"
            if [[ -n "${tokens[-1]}" ]] || [[ -n "${tokens[-2]}" ]]; then
                # There's a token in the last slot in the tokens array, so make a new slot for the next one
                tokens+=("$lineNumber:$columnNumber:$currentIndentLevel")
                tokens+=("")
                tokens+=("")
            fi
            countingIndentSpaces="true"
        elif asciiIsPrintable "$byte"; then
            tokens[-1]="${tokens[-1]} $byte"
        else
            die "Non-printable byte $byte in a comment."
        fi
        ;;
    literal-s)
        if [[ "$byte" == 39 ]]; then
            parserState="token"
            tokens+=("$lineNumber:$columnNumber:$currentIndentLevel")
            tokens+=("")
            tokens+=("")
        elif asciiIsPrintable "$byte"; then
            tokens[-1]="${tokens[-1]} $byte"
        else
            die "Non-printable byte $byte in a comment."
        fi
        ;;
    *)
        die "Unknown parser state $parserState."
        ;;
    esac
done < <(hexdump -v -e '1/1 "%02X\n"' < "$input")

tempIndentLevel="$currentIndentLevel"
for (( i=0; i<tempIndentLevel; i++ )); do
    currentIndentLevel=$(( currentIndentLevel - 1 ))
    pushToken dedent ""
done

pushToken "end-document" ""

tokenCount="${#tokens[@]}"

# If there's an empty token slot at the end, remove it
if [[ -z "${tokens[-1]}" ]] && [[ -z "${tokens[-2]}" ]]; then
    unset 'tokens[-1]'
    unset 'tokens[-1]'
    unset 'tokens[-1]'
fi

# Not all the tokens are identified yet. So, now, let's label them all.

inParameterList="false"
for (( i=0; i<tokenCount; i++ )); do
    if ! (( (i+1) % 3 )); then
        if [[ -z "${tokens[$i - 1]}" ]]; then
            # Set the token names in the table for these that aren't yet identified
            firstByte="${tokens[$i]:1}"
            if asciiIsDigit "${firstByte%% *}"; then
                tokens[$i - 1]="literal-n"
            else
                case "${tokens[$i]}" in
                " 114 47 115 47 "*)
                    tokens[$i - 1]="ident-r-s"
                    tokens[$i]="${tokens[$i]# 114 47 115 47}"
                    ;;
                " 110 47 "*)
                    tokens[$i - 1]="ident-n"
                    tokens[$i]="${tokens[$i]# 110 47}"
                    ;;
                *)
                    tokens[$i - 1]="command"
                    ;;
                esac
            fi
        fi
    fi
done
tokenCount="${#tokens[@]}"

# Convert command & number tokens' labels to strings instead of space-separated ASCII

for (( i=0; i<tokenCount; i++ )); do
    if ! (( (i+1) % 3 )); then
        if [[ "${tokens[$i - 1]}" == "command" ]] || [[ "${tokens[$i - 1]}" == "literal-n" ]]; then
            tokens[$i]="$(asciiDecListToText <<< "${tokens[$i]}")"
        fi
    fi
done

tokenCount="${#tokens[@]}"
#declare -p tokens >&2
echo "Document contains $((tokenCount / 3)) tokens." >&2
for (( i=0; i<tokenCount; i++ )); do
    ! (( (i+1) % 3 )) && echo "Token #$((i / 3 + 1)) (${tokens[$i - 2]}): ${tokens[$i - 1]} ($((i-1))): ${tokens[$i]} ($i)" >&2
done

# We now know what each token is, so let's do the code generation.

if [[ "$targetLang" == "parsed" ]]; then
    # Just dump the parse results and exit
    for (( i=0; i<tokenCount; i++ )); do
        ! (( (i+1) % 3 )) && echo "${tokens[$i - 1]} ${tokens[$i]}"
    done
    true
    exit
fi

codegenIndent=0
codegenRoutineType=""
codegenRoutineName=""
codegenArgList=()

# Define a function for each type of output needed for code generation

codegenType() {
    # First arg: type; second arg: "true" for uppercase first letter
    local result=""
    case "$targetLang" in
    "js")
        [[ "$1" == "ident-s" ]] && result='str'
        [[ "$1" == "ident-n" ]] && result='int'
        [[ "$1" == "ident-arr-s" ]] && result='strArray'
        [[ "$1" == "ident-arr-n" ]] && result='intArray'
        [[ "$1" == "ident-r-s" ]] && result='str'
        [[ "$1" == "ident-r-n" ]] && result='int'
        [[ "$1" == "ident-r-arr-s" ]] && result='strArray'
        [[ "$1" == "ident-r-arr-n" ]] && result='intArray'
        [[ -z "$result" ]] && result="$1"
        if [[ "$2" == "true" ]]; then
            print "${result^}"
        else
            print "$result"
        fi
        ;;
    *)
        die "${FUNCNAME[0]} is not implemented in $targetLang."
        ;;
    esac
}

codegenLiteral() {
    # First arg: type; second arg: value
    case "$targetLang" in
    "js")
        case "$1" in
        "literal-s")
            print \'"$2"\'
            ;;
        esac
        ;;
    *)
        die "${FUNCNAME[0]} is not implemented in $targetLang."
        ;;
    esac
}

codegenPrintIndentationSpaces() {
    for (( j=0; j<codegenIndent; j++ )); do
        print '    '
    done
}

codegenStartDocument() {
    case "$targetLang" in
    "js")
        ;;
    *)
        die "${FUNCNAME[0]} is not implemented in $targetLang."
        ;;
    esac
}

codegenEndDocument() {
    case "$targetLang" in
    "js")
        ;;
    *)
        die "${FUNCNAME[0]} is not implemented in $targetLang."
        ;;
    esac
}

codegenComment() {
    codegenPrintIndentationSpaces
    case "$targetLang" in
    "js")
        print "/*""$1 */"$'\n'
        ;;
    *)
        die "${FUNCNAME[0]} is not implemented in $targetLang."
        ;;
    esac
}

codegenCommandInvocationStart() {
    case "$codegenRoutineName" in
    "return")
        # Return needs its own handling
        case "$targetLang" in
        "js")
            ;;
        *)
            die "${FUNCNAME[0]} is not implemented in $targetLang."
            ;;
        esac
        ;;
    add|eq|mod)
        # These commands are implemented with impl* calls
        case "$targetLang" in
        "js")
            print "await impl${codegenRoutineName^}("
            ;;
        *)
            die "${FUNCNAME[0]} is not implemented in $targetLang."
            ;;
        esac
        ;;
    *)
        codegenPrintIndentationSpaces
        case "$targetLang" in
        "js")
            print "await $codegenRoutineName("
            ;;
        *)
            die "${FUNCNAME[0]} is not implemented in $targetLang."
            ;;
        esac
        ;;
    esac
    codegenRoutineType=""
    codegenRoutineName=""
    codegenArgList=()
}

codegenCommandInvocationEnd() {
    case "$codegenRoutineName" in
    "return")
        # Return needs its own handling
        print $'\n'
        codegenPrintIndentationSpaces
        case "$targetLang" in
        "js")
            codegenType "${blockStack[-2]}"
            print "Return = "
            codegenLiteral "${codegenArgList[-2]}" "${codegenArgList[-1]}"
            print "; await assertIs"
            codegenType "${blockStack[-2]}" true
            print "("
            codegenType "${blockStack[-2]}"
            print "Return); return "
            codegenType "${blockStack[-2]}"
            print "Return;"$'\n'
            ;;
        *)
            die "${FUNCNAME[0]} is not implemented in $targetLang."
            ;;
        esac
        ;;
    add|eq|mod)
        # These commands are implemented with impl* calls
        case "$targetLang" in
        "js")
            print "await impl${codegenRoutineName^}("
            for (( k=0; k<argumentCount; k++ )); do
                if (( k % 2 )); then
                    print "await assertIs"
                    codegenType "${codegenArgList[$k - 1]}" "true"
                    print "("
                    codegenType "${codegenArgList[$k - 1]}"
                    print "${codegenArgList[$k]^}"
                    if [[ "$k" == $((argumentCount - 1)) ]] && [[ "${codegenArgList[$k - 1]}" == "void" ]]; then
                        print ");"
                    else
                        print "); "
                    fi
                fi
            done
            ;;
        *)
            die "${FUNCNAME[0]} is not implemented in $targetLang."
            ;;
        esac
        ;;
    *)
        codegenPrintIndentationSpaces
        case "$targetLang" in
        "js")
            print ")"$'\n'
            ;;
        *)
            die "${FUNCNAME[0]} is not implemented in $targetLang."
            ;;
        esac
        ;;
    esac
    codegenRoutineType=""
    codegenRoutineName=""
    codegenArgList=()
}

codegenRoutineDefinitionStart() {
    case "$targetLang" in
    "js")
        print "async function $codegenRoutineName("
        argumentCount="${#codegenArgList[@]}"
        for (( k=0; k<argumentCount; k++ )); do
            if (( k % 2 )); then
                codegenType "${codegenArgList[$k - 1]}"
                if [[ "$k" == $((argumentCount - 1)) ]]; then
                    print "${codegenArgList[$k]^}"
                else
                    print "${codegenArgList[$k]^}, "
                fi
            fi
        done
        print ") {"$'\n'
        codegenIndent=$(( codegenIndent + 1 ))
        codegenPrintIndentationSpaces
        codegenIndent=$(( codegenIndent - 1 ))
        for (( k=0; k<argumentCount; k++ )); do
            if (( k % 2 )); then
                print "await assertIs"
                codegenType "${codegenArgList[$k - 1]}" "true"
                print "("
                codegenType "${codegenArgList[$k - 1]}"
                print "${codegenArgList[$k]^}"
                if [[ "$k" == $((argumentCount - 1)) ]] && [[ "${codegenArgList[$k - 1]}" == "void" ]]; then
                    print ");"
                else
                    print "); "
                fi
            fi
        done
        if [[ "${codegenArgList[$k - 1]}" != "void" ]]; then
            print "let "
            codegenType "$codegenRoutineType"
            print "Return;"$'\n\n'
        fi
        ;;
    *)
        die "${FUNCNAME[0]} is not implemented in $targetLang."
        ;;
    esac
    codegenRoutineType=""
    codegenRoutineName=""
    codegenArgList=()
}

codegenRoutineDefinitionEnd() {
    case "$targetLang" in
    "js")
        print "}"$'\n'
        ;;
    *)
        die "${FUNCNAME[0]} is not implemented in $targetLang."
        ;;
    esac
}

# Set up the variables we'll need for going through the tokens and generating the code

stateStack=("code")
blockStack=("root" "")

for (( i=0; i<tokenCount; i++ )); do
    if ! (( (i+1) % 3 )); then
        codegenIndent="${tokens[$i - 2]##*:}"

        echo >&2
        echo "State: ${stateStack[-1]}, token #$((i / 3 + 1)) (${tokens[$i - 2]}): ${tokens[$i - 1]} ($((i-1))): ${tokens[$i]} ($i)" >&2
        declare -p stateStack >&2

        if [[ "${tokens[$i - 1]}" == "comment" ]]; then
            echo "(Inserting a comment)" >&2
            codegenComment "$(asciiDecListToText "${tokens[$i]}")"
        else
            case "${stateStack[-1]}" in
            code)
                echo "Working on code" >&2
                case "${tokens[$i - 1]}" in
                start-document)
                    codegenStartDocument
                    ;;
                end-document)
                    codegenEndDocument
                    ;;
                indent)
                    #codegenIndent=$((codegenIndent + 1))
                    stateStack+=("code")
                    ;;
                dedent)
                    #codegenIndent=$((codegenIndent - 1))
                    unset 'stateStack[-1]'
                    ;;
                ident-r-*)
                    codegenRoutineName="$(asciiDecListToText "${tokens[$i]}")"
                    codegenRoutineType="${tokens[$i - 1]}"
                    stateStack+=("routine-definition")
                    blockStack+=("${tokens[$i - 1]}" "${tokens[$i]}")
                    ;;
                command)
                    codegenRoutineName="${tokens[$i]}"
                    stateStack+=("arglist")
                    codegenCommandInvocationStart
                    ;;
                newline)
                    ;;
                *)
                    die "A ${tokens[$i - 1]}, ${tokens[$i]}, isn't allowed here, in ${blockStack[-1]}."
                    ;;
                esac
                ;;
            arglist)
                echo "Working on arglist" >&2
                case "${tokens[$i - 1]}" in
                literal-*)
                    # Some type of data, literal.
                    codegenArgList+=("${tokens[$i - 1]}" "$(asciiDecListToText "${tokens[$i]}")")
                    ;;
                ident-*)
                    # Some type of data, reference.
                    codegenArgList+=("${tokens[$i - 1]}" "$(asciiDecListToText "${tokens[$i]}")")
                    ;;
                command)
                    codegenRoutineName="${tokens[$i]}"
                    stateStack+=("arglist")
                    ;;
                *)
                    # The arglist is ended, so do codegen for the command invocation, drop back and continue parsing.
                    codegenCommandInvocationEnd
                    unset 'stateStack[-1]'
                    i=$((i - 3))
                    ;;
                esac
                ;;
            routine-definition)
                echo "Working on routine definition" >&2
                # Format: token, [ident...], code body
                # So now we look for as many types as there are. When no more types, it enters the code body of the routine. When there's a dedent, it leaves the code body of the routine.
                case "${tokens[$i - 1]}" in
                ident-*)
                    # Some type of data, reference.
                    codegenArgList+=("${tokens[$i - 1]}" "$(asciiDecListToText "${tokens[$i]}")")
                    ;;
                indent|newline)
                    # The routine definition parameter list is ended, so do codegen for the routine declaration (but not the body of it), and continue parsing.
                    codegenRoutineDefinitionStart
                    stateStack[-1]="routine-definition-end"
                    stateStack+=("code")
                    # Avoid putting in an extra code level
                    [[ "${tokens[$i - 1]}" == "newline" ]] && [[ "${tokens[$i + 2]}" == "indent" ]] && i=$((i + 3))
                    ;;
                *)
                    die "Routine definition unexpected token type"
                esac
                ;;
            routine-definition-end)
                echo "Working on routine definition end" >&2
                unset 'stateStack[-1]'
                codegenRoutineDefinitionEnd
                unset 'blockStack[-1]'
                unset 'blockStack[-1]'
                ;;
            *)
                die "Unimplemented code generation state ${stateStack[-1]}"
                ;;
            esac
        fi
    fi
done

print_r "${stateStack[@]}" >&2
print_r "${blockStack[@]}" >&2
