#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Setup:
# in one terminal, run: cd '/Ember Library/Ember/ember-information-technology-environment'; cat >> ./stagel-converter-gui-doc.stagel
# Move that terminal to the upper left.
# In another terminal, run: cd '/Ember Library/Ember/ember-information-technology-environment'; watch -n .3 cat ./stagel-converter-gui-example.stagel
# Move that terminal to the lower left.
# In another terminal, run: cd '/Ember Library/Ember/ember-information-technology-environment'; watch -n .3 cat ./stagel-converter-gui-doc-output.js
# Move that terminal to the upper right.
# In a third terminal, run: cd '/Ember Library/Ember/ember-information-technology-environment'; ./stagel-converter-gui
# Move that terminal to the lower right.

while true; do
    zenity --info --text="Type your program in the upper left area.
    An example program is shown in the lower left area.
    Click OK to convert the program!
    It will show up in the upper right area, as JavaScript."

    stagel-convert "./stagel-converter-gui-doc.stagel" "js" > "./stagel-converter-gui-doc-output.js"

    eogup-single

    rm "./stagel-converter-gui-doc.stagel"
    touch "./stagel-converter-gui-doc.stagel"
done
