#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Build the StageL library. Also build StageR while we're at it.

slcmd="stagel-build-internal-stagel-inner"
[[ -f "./stagel-build-internal-stagel-inner" ]] && slcmd=./"$slcmd"
srcmd="stagel-build-internal-stager-inner"
[[ -f "./stagel-build-internal-stager-inner" ]] && srcmd=./"$srcmd"

targets=(js sh)

targetCount="${#targets[@]}"
for (( i=0; i<targetCount; i++ )); do
    #StageL
    [[ -d "./stagel-resources/${targets[$i]}" ]] || continue

    rm -f ./stagel-resources/"${targets[$i]}"/stagel."${targets[$i]}"

    find ./stagel-resources/"${targets[$i]}"/ -name '*.'"${targets[$i]}" -exec "$slcmd" {} "${targets[$i]}" \;

    #StageR
    [[ -d "./stagel-resources/${targets[$i]}" ]] || continue

    rm -f ./stagel-resources/stager/stager."${targets[$i]}"

    find ./stagel-resources/stager/ -name '*.stagel' -exec "$srcmd" {} "${targets[$i]}" \;
done
