#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Setup:
# In one terminal, run: cd '/Ember Library/Ember/ember-information-technology-environment/cli/'; cat ./stagel-converter-gui-example.stagel
# Move that terminal to the lower left.
# In a second terminal, run: cd '/Ember Library/Ember/ember-information-technology-environment/cli/'; watch -n .3 cat ./stagel-converter-gui-doc-output.js
# Move that terminal to the right.
# In a third terminal, run: cd '/Ember Library/Ember/ember-information-technology-environment/cli/'; ./stagel-converter-gui
# Move that terminal to the upper left.

while true; do
    clear
    echo "Type your program here.
    An example program is shown in the lower left area.
    Press Alt+C when you are done, and your program will be converted.
    It will show up in the right area, as JavaScript."

    cat >> ./stagel-converter-gui-doc.stagel 2>/dev/null || true

    ./stagel-convert "./stagel-converter-gui-doc.stagel" "js" > "./stagel-converter-gui-doc-output.js" || true

    eogup-single || true

    rm "./stagel-converter-gui-doc.stagel" || true
    touch "./stagel-converter-gui-doc.stagel"
done
