#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Build the StageR library

cmd="stagel-build-internal-stager-inner"
[[ -f "./stagel-build-internal-stager-inner" ]] && cmd=./"$cmd"

targets=(js sh)

targetCount="${#targets[@]}"
for (( i=0; i<targetCount; i++ )); do
    [[ -d "./stagel-resources/${targets[$i]}" ]] || continue

    rm -f ./stagel-resources/stager/stager."${targets[$i]}"

    find ./stagel-resources/stager/ -name '*.stagel' -exec "$cmd" {} "${targets[$i]}" \;
done
