#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

fileName="$1"

match="\.em$"
if [[ "$fileName" ~= $match ]]; then
    format="EM"
fi
match="\.emd$"
if [[ "$fileName" ~= $match ]]; then
    format="EMD"
fi
match="\.ems$"
if [[ "$fileName" ~= $match ]]; then
    format="EMS"
fi
match="\.dems$"
if [[ "$fileName" ~= $match ]]; then
    format="DEMS"
fi
[[ -z "$format" ]] && die "Unknown format."
tempFileId="em-tmp-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
cp "$fileName" "/tmp/$tempFileId"

dcData="/Ember Library/Ember/ember-information-technology-environment/common/data/DcData.csv"
asciiMapping="/Ember Library/Ember/ember-information-technology-environment/common/data/mappings/from/ascii.csv"

# Convert file to .ems file for working

# Replace all spaces with newlines
ereplace ' ' $'\n' "/tmp/$tempFileId"

# Parse file
while read dc; do
    # Handle individual Dc
    if grep ",$dc," "$asciiMapping"; then
        grep ",$dc," "$asciiMapping" | awk -F "\"*,\"*" '{print $2}'
done <"/tmp/$tempFileId"
