#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

cat GeneralSupport.p6 Grammar.p6 ExportXML.p6 TestSupport.p6 > .parseDocument.p6

chmod +x .parseDocument.p6

print "say" | ./.parseDocument.p6
