#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

eite-single-test() {
    testPath="$1"
    runInput="$(tempFile)"
    runOutput="$(tempFile)"
    if [[ -d "$testPath" ]]; then
        cp "$testPath/in.eite" "$runInput"
        cp "$testPath/out" "$runOutput"
    else
        die "TODO: not implemented"
    fi
    assert fileEquals 
}

find -name '.eite-test' "$(dirname "$(crystallize-getconf ConfigLocation)")/usr/eite/tests" -exec runTest eite-single-test {} \;
