#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Build the StageL library. Also build StageR while we're at it.

sicmd="stagel-build-internal-wrapped"
[[ -f "./stagel-build-internal-wrapped" ]] && sicmd=./"$sicmd"

if [[ "$1" == "-v" ]]; then
    shift
    "$sicmd" "$@"
else
    echo "Building, please wait..."
    "$sicmd" "$@" &> /dev/null
    echo "Done."
fi

cp ./stagel-resources/core-implementations/js/stagel.js ../web/eite.js
echo >> ../web/eite.js
cat ./stagel-resources/stager/stager.js >> ../web/eite.js
echo >> ../web/eite.js
cat ./stagel-resources/speedups/speedups.js >> ../web/eite.js
