#!/bin/bash
dir="$1"
cmd="$2"
if [[ "" == "$cmd" ]]; then
    cmd="mkdir -p"
fi
cd "$dir" || die
i=0
gencmd="../gen"
[[ -e "./gen" ]] || gencmd="../../gen"
#a=$'150'; mkdir "$a"
while [[ "$i" -lt 500 ]]; do
    bash -c 'a=$'\'\\"$i"\''; '"$cmd"' "$a"'
    if [[ "touch" != "$cmd" ]]; then
        bash -c 'a=$'\'\\"$i"\''; '"$cmd"' "$a"; cd "$a"; '"$gencmd"' "$(pwd)" "touch"'
    fi
    i=$(( i + 1 ))
done