#!/bin/bash
dir="$1"
cmd="$2"
if [[ "" == "$cmd" ]]; then
    cmd="mkdir -p"
fi
cd "$dir" || die
i=0
gencmd="../gen"
[[ -e "$gencmd" ]] || gencmd="../../gen"
while [[ "$i" -lt 500 ]]; do
    bash -c "$cmd"' $'\'"$i"\''; cd $'\'"$i"\''; pwd; '"$gencmd"' "$(pwd)" "touch"'
    i=$(( i + 1 ))
done