#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Create Web extension version of edit tool

rm -rf ./built/web
mkdir ./built/web
cp -r ./implementation/platform-support/web/* ./built/web/
#cp ./built/dist-built/wabt/* ./built/web/
rm -rf ./built/web/data
cp ./built/stagel-parts/js/eite.js ./built/web/
cp -r ./data ./built/web/
#cp -r ./built/wasm-common ./built/web/
cp /usr/share/futuramerlin-web-toolkit/assets/*.css ./built/web/
cp ./LICENSE* ./built/web/
rm ./built/web/papaparse.js
cp /usr/share/javascript/PapaParse/papaparse.js ./built/web/
