#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Create Web extension version of edit tool

rm -rf ./built/web
mkdir ./built/web
cp -r ./implementation/platform-support/web/* ./built/web/
cp ./implementation/core-implementations/js/core.js ./built/web/eite.js
echo >> ./built/web/eite.js
cat ./implementation/portable/portable.js >> ./built/web/eite.js
echo >> ./built/web/eite.js
echo '// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0'$'\n' >> ./built/web/eite.js
cat ./implementation/speedups/speedups.js >> ./built/web/eite.js
echo $'\n''// @license-end' >> ./built/web/eite.js
rm -rf ./built/web/data
cp -r ./data ./built/web/
cp /usr/share/futuramerlin-web-toolkit/assets/*.css ./built/web/
cp ./LICENSE* ./built/web/
