#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

if [[ -e "./build-temp/dist-already-unpacked" ]]; then
    echo "Distfiles were already unpacked. Nothing to do."
fi

source ./support/build-scripts/dist-versions || die

[[ -d ./build-temp/distfiles ]] || die "Make sure the required dependency files are in ./build-temp/distfiles, or run support/dist-fetch to get them from your /usr/portage."

rm -rf ./build-temp/unpacked
cp -ra ./build-temp/distfiles ./build-temp/unpacked

# Unpack distfiles

(
cd ./build-temp/unpacked || die

echo "Unpacking Unicode"
mkdir "./ucd.all.flat-${myUnicodeVersion}/"
unzip "./ucd.all.flat-${myUnicodeVersion}.zip" -d "./ucd.all.flat-${myUnicodeVersion}/"
rm "./ucd.all.flat-${myUnicodeVersion}.zip"
)
